pipelineType: php
phpTool: php-8.1
runSonar: true

composerRunScripts:
  init: jenkins-init
  build: jenkins-build
  test: jenkins-test

provisionFor:
  - release_dev
  - develop
  - master
  - release_12.3.3
