<?php

namespace App\Features\Batch\Constants;

class BatchConstant
{
  // ACTIVE VS IN ACTIVE
  const ACTIVE = 'Y';
  const IN_ACTIVE = 'N';

  const ON_DEMAND_YES = 'Y';
  const ON_DEMAND_NO = 'N';

  const ALLOW_OVERLAPPING_YES = 'Y';
  const ALLOW_OVERLAPPING_NO = 'N';

  const BATCH_CATEGORY_GENERAL = 'GENERAL';

  const BATCH_SCHEDULE_STATUS_READY = 'READY';
  const BATCH_SCHEDULE_STATUS_RUNNING = 'RUNNING';
  const BATCH_SCHEDULE_STATUS_ERROR = 'ERROR';
  const BATCH_SCHEDULE_STATUS_COMPLETED = 'COMPLETED';
  
  // AUDIT LOG
  const AUDIT_LOG_CATEGORY = 'BATCH';
  const AUDIT_LOG_EVENT_STARTED = 'BATCH-STARTED';
  const AUDIT_LOG_EVENT_RUN = 'BATCH-RUN';
  const AUDIT_LOG_EVENT_ENDED = 'BATCH-ENDED';
  const AUDIT_LOG_EVENT_EXCEPTION = 'BATCH-EXCEPTION';
  const AUDIT_LOG_EVENT_INSERT = 'BATCH-INSERT';
  const AUDIT_LOG_EVENT_UPDATE = 'BATCH-UPDATE';
  const AUDIT_LOG_EVENT_DELETE = 'BATCH-DELETE';
  const AUDIT_LOG_EVENT_KILLED = 'BATCH-KILLED';

}
